- CHANGELOG.md
- asf_tools/composite.py
- conda-env.yml
- setup.py
- tests/test_entrypoints.py
This bring in the David Small mosaic code from hyp3-stacking into `asf_tools`. 
`src/make_composite.py` has been renamed to `asf_tools/composite.py`, and all previous history was included.
The hyp3-stacking history was filtered and rewritten using [git-filter-repo](https://github.com/newren/git-filter-repo) by running these commands:
```sh
git clone git@github.com:asfadmin/hyp3-stacking.git
cd hyp3-stacking
git filter-repo \
--path src/make_composite.py \
--path-rename 'src/make_composite.py':'asf_tools/composite.py'
git remote add asf-tools git@github.com:ASFHyP3/asf-tools.git
git push -u asf-tools test:add-composite
cd ..  # back to asf-tools
git fetch --all
git merge --no-ff --allow-unrelated-histories origin/add-composite
```
> Add David Small (local resolution weighting) mosaics

- .github/workflows/static-analysis.yml
- asf_tools/composite.py
- tests/test_composite.py
* use `multimode` to determine hemisphere; in the event of a tie, choose lowest valued (North).
* re-implement median to choose lowest zone of median two when an even number of zones are given
* no numpy dep. for this now
> Simplify EPSG find and always handle antimerridian

- asf_tools/composite.py
Resolves https://github.com/ASFHyP3/asf-tools/issues/34
@talogan does this fit with your workflow?  I think this is the most straightforward approach; asking the user to provide the output filename without any extension, to which we append `.tif` and `_counts.tif`
> better handling of output file names

- asf_tools/composite.py
This removes the large nodata regions from overviews.  See descriptions of resampling methods at https://gdal.org/programs/gdaladdo.html#cmdoption-gdaladdo-r
hyp3lib.make_cogs previously used `-r average` when generating overviews as well.
For reference, this list of all creation options for the COG driver are at https://gdal.org/drivers/raster/cog.html#creation-options
> use AVERAGE overview resampling for better nodata handling

- asf_tools/composite.py
Incremental logging improvements.  A subsequent PR can revise the logged messages themselves.
- use module logger rather than root logger
- use default date format (`YYYY-MM-DD HH:MI:SS,NNN`)
- move start/end logging out of `make_composite()` to `main()`
- add `--verbose` option to `main()` to control log level rather than always setting level to `DEBUG`
- log only to `STDOUT`, with the intent that command line users can redirect `STDOUT` to a file if desired
Makes progress on https://github.com/ASFHyP3/asf-tools/issues/43
> Logging improvements

- asf_tools/composite.py
Here's the example default output.  Setting `--verbose` or `level=logging.DEBUG` still gets you most of the old messages.
```
2020-12-01 11:43:17,137 - INFO - Starting run
2020-12-01 11:43:17,164 - INFO - Reprojecting S1A_IW_20181102T155531_DVP_RTC30_G_gpuned_5685/S1A_IW_20181102T155531_DVP_RTC30_G_gpuned_5685_VV.tif
2020-12-01 11:43:20,326 - INFO - Reprojecting S1A_IW_20181102T155531_DVP_RTC30_G_gpuned_5685/S1A_IW_20181102T155531_DVP_RTC30_G_gpuned_5685_area.tif
2020-12-01 11:43:23,519 - INFO - Reprojecting S1A_IW_20181102T155556_DVP_RTC30_G_gpuned_7C8B/S1A_IW_20181102T155556_DVP_RTC30_G_gpuned_7C8B_VV.tif
2020-12-01 11:43:26,711 - INFO - Reprojecting S1A_IW_20181102T155556_DVP_RTC30_G_gpuned_7C8B/S1A_IW_20181102T155556_DVP_RTC30_G_gpuned_7C8B_area.tif
2020-12-01 11:43:29,870 - INFO - …
```
> send logs to stdout, reduce number of log.info messages

- asf_tools/composite.py
* Descriptive docstring for composite module; also used as CLI description
* drop `--path` and `--pol` arguments in favor of users selecting their own input files
* `rasters` (previously `infiles`) is now a required positional argument that needs at least 1 raster
* `make_composite` function raises a `ValueError` when no input rasters provided
* argument names and `make_composite` function arguments are now uniform
Minor things:
* cleaned up some of the logging in `main`
* double -> single quote strings in main 
Current CLI `--help`:
```
usage: make_composite.py [-h] [-r RESOLUTION] [-v] out_name rasters [rasters ...]
Create an inverse area weighted composite mosaic from Sentinel-1 RTC products.
Create a composite mosaic from a set of Sentinel-1 RTC products using
local area weighting (D. …
```
> CLI improvements

- .github/workflows/release.yml
- asf_tools/README.md
- asf_tools/composite.py
* Adds more information about environments to installation
* Fixes page title heading size
* updates the release workflow to use the `bump ASF Tools version` workflow dispatch, which will be available with ASFHyP3/ASFHyP3#41
> Update README and hyp3-docs workflow

- CHANGELOG.md
- asf_tools/util.py
- tests/test_util.py
A critical step to surface water extent mapping is breaking a scene down into a set of sub-scenes (tiling), see first figure in:
https://github.com/fjmeyer/HydroSAR/blob/master/HYDRO30Workflow-v1.ipynb
This adds tiling (and untiling) utility functions to perform that duty.
> Array tiling and untiling

- CHANGELOG.md
- asf_tools/raster.py
- tests/test_raster.py
Will need to switch from Power to db when doing the expectation maximization thresholding.
Of note: This is based on what @hjkristenson did for the ArcGIS toolbox, but doesn't look exactly like the db conversion in the notebooks:
```python
db = np.log10(power)+30
```
> Add a scale conversion function

- asf_tools/raster.py
- tests/test_raster.py
`raster.py` hasn't been released yet, so changelog is current still
reordered tests to "what you got compared to what you shoulda got" convention
> Allow raster scale conversion to handle masked arrays

- asf_tools/hand/prepare.py
- asf_tools/water_map.py
A few improvements from Franz intended to:
* Tweak the HAND upper limit calculation to prevent correct water pixels from being removed (due to random noise from vegetation)
* Drop the morphological filter step
* reduce the unnecessary work in the area membership segmentation
---
Previously, we generated a golden map that looks like this (note: overview):
Now, we're creating a map like this:
which picks up a bit more water pixels from the initial map:
> Watermap improvements

- asf_tools/water_map.py
* Updates default thresholds based on [v2 notebook](https://github.com/fjmeyer/HydroSAR/blob/master/HYDRO30Workflow-v2.ipynb)
* Fixes:
* CLI default vh threshold being different than python fn
* segments above threshold masking
* `isin` should have been looking at `segments` not `segment_membership`
* need to *not* include segment of zero-values
> Minor patches to watermap code

- CHANGELOG.md
- asf_tools/water_map.py
- tests/test_water_map.py
Currently, if the HAND is completely flat (e.g., ocean scene), water mapping code will fail in fuzzy refinement with a very undescriptive error:
```
Traceback (most recent call last):
...
File ".../asf_tools/water_map.py", line 272, in make_water_map
water_map = fuzzy_refinement(
File ".../asf_tools/water_map.py", line 141, in fuzzy_refinement
hand_membership = min_max_membership(hand_array, hand_lower_limit, hand_upper_limit, 0.1)
File ".../asf_tools/water_map.py", line 96, in min_max_membership
activation = fuzz.zmf(possible_values, lower_limit, upper_limit)
File ".../lib/python3.9/site-packages/skfuzzy/membership/generatemf.py", line 476, in zmf
assert a <= b, 'a <= b is required.'
AssertionError: a <= b is required.
```
This fails much earlier by checking for a flat hand upfront and …
> raise error when hand is flat

- CHANGELOG.md
- asf_tools/hand/calculate.py
Using the `Path` type for the `hand_raster` and `vector_file` prevents using `/vsicurl` and `/vsis3` because it reduces double `//`s to `/` as seen in this logging output:
```
2022-03-25 10:07:16,736 - INFO - Calculating HAND for /vsicurl/https:/hyp3-testing.s3-us-west-2.amazonaws.com/asf-tools/hand/hybas_af_lev12_v1c_firstpoly.geojson
```
and causes a GDAL/Rasterio/Fiona error when trying to access the path.
`calculate_hand` takes either a `str` or a `Path` so using the default `str` type in argparse fixes the issue.
> Bugfix: vsi paths to calculate_hand entrypoint

- asf_tools/dem.py
- tests/test_vector.py
This:
1. switches to the 2021 COP30 DEM release
2. switches to the ASF DEM mirror in `us-west-2` instead of `eu-central-1`
For (2), we aren't using `prepare_dem_vrt` except for calculating the HAND (water products are using the DEM GeoTIFF in the RTC products. I'm not sure if we want to (a) always point to the canonical bucket or (b) point to our mirror. Thoughts?
> Use the 2021 COP30 release

- asf_tools/hand/handcloudformation.yml
If we're running 26,000 jobs at least a few will fail with transient errors (e.g. failed network connections). This PR adds a [RetryStrategy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html) to the job definition so that those jobs that failed will be automatically retried twice.
> retry batch jobs on failure

- .github/workflows/release.yml
Dispatch workflow failed last release:
because we stopped providing the `token:` argument when we upgraded the version in #150 . Even though it's no longer needed for triggering workflows in the same repo, it is required to trigger workflows in different repos:
https://github.com/benc-uk/workflow-dispatch#repo
This adds the token back.
> provide token to dispatch action

- src/asf_tools/__init__.py
Lingering setup.py reference from the change to src format and pyproject.toml. Removed this reference and an unnecessary error message.
> remove setup.py reference and unnecessary error message

- CHANGELOG.md
- environment.yml
Numpy 1.24 includes the removal of a lot of outstanding depreciations and was causing pytest to fail with:
```
ERROR tests/test_hand.py - SystemError: initialization of _internal failed without raising an exception
ERROR tests/test_vector.py - SystemError: initialization of _internal failed without raising an exception
ERROR tests/test_water_map.py - SystemError: initialization of _internal failed without raising an exception
```
Traceback for one of the tests:
```
___________________ ERROR collecting tests/test_water_map.py ___________________
tests/test_water_map.py:5: in <module>
from asf_tools import water_map
/usr/share/miniconda/envs/asf-tools/lib/python3.9/site-packages/asf_tools/water_map.py:21: in <module>
from asf_tools.hand.prepare import prepare_hand_for_raster …
```
> Unrestrict NumPy in environment

- src/asf_tools/flood_map.py
- src/asf_tools/water_map.py
Currently, the contents of the output zip archive for water map and flood map jobs is structured like:
```
home/
└── conda/
└── product-name/
```
This fixes the `make_archive` command so that the output zip archive contains a single `product-name/` directory.
Tested locally with the water map `hyp3` entrypoint.
> Fix water_map and flood_map zip paths

- src/asf_tools/aws.py
- tests/test_aws.py
The previous code to fetch the input RTC image for water_map or the input water map images for flood_depth didn't work in EDC environments where the content bucket isn't public, e.g.:
```
Found VV raster: /vsicurl/https://hyp3-edc-uat-contentbucket-XXXXXXX.s3.amazonaws.com/f9ff8a26-1890-408e-8050-f27d126e64c4/S1A_IW_20221201T133515_DVP_RTC30_G_gpufed_9BF9_VV.tif
RuntimeError: HTTP response code: 403
```
`get_path_to_s3_file()` returned a /vsicurl path, which doesn't immediately work with private buckets, even if the EC2 machine has valid AWS credentials with the correct permissions. Updating the function to return a /vsis3 path resolves the issue.
> return /vsis3 path from aws.get_path_to_s3_file

- .github/workflows/distribute.yml
- CHANGELOG.md
- src/asf_tools/flood_map.py
- Update GH actions to use `checkout@v3
- Update `flood_map` so that a nodata value indicates a lack of imagery, and 0 indicates a lack of flooding.
* patch -- Patches and bugfixes for the current version that do not break current workflows
> Release v0.5.1

- src/asf_tools/flood_map.py
Even though we allow the `known_water_threshold` to be `null` in HyP3 (https://github.com/ASFHyP3/hyp3/pull/1634) and it *is* `null` in the API responses and DynamoDB, when we execute the step function we convert everything to strings:
https://github.com/ASFHyP3/hyp3/blob/develop/apps/start-execution-worker/src/start_execution_worker.py#L12-L19
which in Python looks like:
```python
>>> str(None)
'None'
```
because `null` objects get represented as `None` in Python.
That means that the  docker run command actually looks like `... --known-water-threshold None ...` .
Since it makes more sense to represent the optional threshold in python by an `Optional[float]` than using `np.nan`, let's go back to `None` to represent no threshold provided.
> Null back to None

- .github/workflows/distribute.yml
PyPI uses a CDN so we'd need to add a delay to this job. I've not actually seen a successful push to PyPI not then be pip installable, so I think we can just drop this instead.
> Don't verify PyPI distributions

- CHANGELOG.md
- src/asf_tools/README.md
This PR replaces the relative link with the full URL for the watermasking readme so that the link will also work in hyp3-docs, which references this readme file for the asf_tools information page.
> Change readme link to full URL

- .github/workflows/tag-version.yml
- .github/workflows/test-and-build.yml
- CHANGELOG.md
- environment.yml
- prototype/osl-env.yml
- pyproject.toml
This PR sets the minimum Python version to 3.10.
> Remove Support for Python 3.8 and 3.9

- .github/workflows/release.yml
- CHANGELOG.md
> switch from repo-sync/pull-request to gh pr create

- .github/workflows/test-and-build.yml
- CHANGELOG.md
- src/asf_tools/raster.py
- Fixes #270
Rasters with `nan` nodata values are returned as masked arrays with no masks (data.mask == np.False_). 
This happened because `nan` == `nan` evaluates to False, as does `np.nan` == `None`.
A nodata value of `nan` enters the branch:
```
if nodata is not None:
return np.ma.masked_values(data, nodata)
```
Then, `np.ma.masked_values(data, nodata)` masks all values where `np.nan` == `np.nan`, which never evaluates to `True` and therefore results in no mask.
`ds` is now deleted, regardless of branching.
> update read_as_masked_array to handle nan nodata values
