ASFHyP3/asf-tools

- ArcGIS-toolbox/ASF_Tools.pyt
flake8 --max-line-length=120 --import-order-style=pycharm --statistics
> reformatted file to pass flake8 (command in body)

- .github/workflows/tag.yml
> fix tag action

- ArcGIS-toolbox/ASF_Tools.pyt
> Syncing with develop 

- .github/workflows/release.yml
> Fix building the Arc toolbox zip name

- .github/workflows/release.yml
> Trigger rebuild of HyP3 docs to pull in current release

- .github/pull_request_template.md
- .github/workflows/tag.yml
- ArcGIS-toolbox/ASF_Tools.pyt
- CHANGELOG.md
- README.md
- conda-env.yml
This makes the necessary changes for renaming the repository `ASF-tools`. 
**It should be merged after the rename.**
> Change all GIS-tools to ASF-tools

- asf_tools/composite.py
> Drop get pol

- asf_tools/composite.py
> Drop unused frange function

- asf_tools/composite.py
- tests/test_composite.py
> Refactor EPSG

- conda-env.yml
- setup.py
Resolves https://github.com/ASFHyP3/asf-tools/issues/36
> remove hyp3lib from setup.py and conda-env.yml

- asf_tools/composite.py
- tests/test_composite.py
Resolves https://github.com/ASFHyP3/asf-tools/issues/33
> use tempfile.TemporaryDirectory for reprojected files

- asf_tools/composite.py
> move path search for rasters to deticated function for srp

- asf_tools/composite.py
Profile:
* Red: Initial implementation
* Black: After writing cogs
* Blue: This PR
Overall reduction in peak memory at a minor runtime expense. 
Note: Using numpy masked arrays is identical memory wise to this PR, but comes at a decent runtime expense since we're not leveraging the masking
> Reduce memory burden

- conda-env.yml
- setup.py
Resolves https://github.com/ASFHyP3/asf-tools/issues/50
> require gdal>=3.2.0 for COG driver and OVERVIEW_RESAMPLING

- asf_tools/composite.py
> convert double quotes to single quotes

- asf_tools/composite.py
Team discussion determined it's worth using David Small's language, even if it obscures the methodology.
> Use David Small's language for composite tool

- asf_tools/composite.py
> fix indent in write_cog()

- tests/test_composite.py
> add test for write_cog()

- tests/test_composite.py
> add test for make_composite

- asf_tools/composite.py
> add missing docstrings

- .github/workflows/test-and-build.yml
- CHANGELOG.md
> Update actions for v2 and changelog for pending release

- .github/workflows/release.yml
- .github/workflows/test-and-build.yml
- ArcGIS-toolbox/ASF_Tools.pyt
- conda-env.yml
Reflects changes in ASFHyP3/hyp3-docs#56
> Change docs repo

- CHANGELOG.md
- asf_tools/threshold.py
- asf_tools/water_map.py
- setup.py
- tests/conftest.py
- tests/test_entrypoints.py
- tests/test_water_map.py
This is an initial implementation of water mapping via Kittler-Illingworth Thresholding. It works on the initial image provided by Fritz et al. but I haven't tested it with other images. 
Example Scene:
Water map overlaid in white:
> Generate a water map using Kittler-Illingworth Thresholding

- asf_tools/util.py
- asf_tools/water_map.py
- tests/test_util.py
> Tile/untile handle numpy MaskedArrays

- asf_tools/hand/prepare.py
- asf_tools/water_map.py
Also:
* fix "transform" typo
* add resampling method to prepare hand for raster
> More Fixes -- upside-down HAND, drop small segments

- CHANGELOG.md
- environment.yml
> Pin numpy version

- CHANGELOG.md
- asf_tools/water_map.py
- environment.yml
> Use nanpercentile to fix #99

- CHANGELOG.md
- asf_tools/water_map.py
- environment.yml
> Release v0.3.2

- CHANGELOG.md
- environment.yml
- setup.py
> Update pysheds and Changelog

- CHANGELOG.md
- asf_tools/hand/calculate.py
- environment.yml
- setup.py
update the calculate_hand code in the asf-tools according to the update of the HydroSAR package.
> Hand update

- CHANGELOG.md
- asf_tools/hand/calculate.py
- environment.yml
- setup.py
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release v0.3.3

- asf_tools/flood_map.py
- setup.py
> Flood maps refactor

- asf_tools/flood_map.py
> Added type hints

- asf_tools/flood_map.py
> Save depth rasters as floats

- asf_tools/flood_map.py
> Change touple to two float args for iterative bounds

- asf_tools/flood_map.py
> Change float to int

- .github/CODEOWNERS
> add CODEOWNERS to automatically request PR reviews

- asf_tools/flood_map.py
`get_waterbody()` was always writing it's scratch file to `data/surface_water_map_clip.tif`. Multiple, simultaneous invocations in the same environment would try to read/write from the same file at the same time.
This PR uses [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) so separate invocations will use separate scratch files. The scratch file will also now be removed from disk automatically.
> used named temporary file in get_waterbody

- asf_tools/flood_map.py
- tests/test_flood_map.py
> Changed estimator default to iterative

- CHANGELOG.md
> update changelog for minor release

- asf_tools/hand/calculate.py
> Refactor HAND improvements

- CHANGELOG.md
- asf_tools/flood_map.py
> Update flood map

- tests/test_flood_map.py
> change logstat function to isclose

- CHANGELOG.md
- asf_tools/hand/calculate.py
> Provide accumulation threshold option throughout hand calculation methods

- CHANGELOG.md
- asf_tools/flood_map.py
- environment.yml
- setup.py
- tests/test_flood_map.py
Also, fixes the flood depth tifs to actually remove the perennial water layer
> Prevent flood depths from being calculated in an S1 scene's no-data values. 

- CHANGELOG.md
- asf_tools/flood_map.py
- asf_tools/hand/calculate.py
- environment.yml
- setup.py
- tests/test_flood_map.py
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release v0.4.2

- asf_tools/hand/launch_hand_campaign.py
- asf_tools/hand/produce_upload_hand.py
> add initial script to launch batch jobs for hand campaign

- asf_tools/hand/launch_hand_campaign.py
- asf_tools/hand/produce_upload_hand.py
> resolve flake8 issues

- asf_tools/water_map.py
> add in function for raster data format

- asf_tools/water_map.py
> add docstring

- CHANGELOG.md
- asf_tools/hand/prepare.py
- asf_tools/water_map.py
- tests/test_vector.py
> Release v0.4.4

- src/asf_tools/hand/calculate.py
> uniform 'ing's

- .github/workflows/changelog.yml
- .github/workflows/distribute.yml
- .github/workflows/labeled-pr.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tag-version.yml
- .github/workflows/test-and-build.yml
> Update CI/CD workflow to v0.7.0

- CHANGELOG.md
- src/asf_tools/water_map.py
> Remove fuzzy and intial VV and VH files

- CHANGELOG.md
- src/asf_tools/water_map.py
Undoes [this commit](https://github.com/ASFHyP3/asf-tools/commit/a65feffd5e01e7b9ba5987e6270f88d12993e29d#diff-dc6503a1d279395a4c0c23002fb5ca15b405570d6f3ee58c4626ef0fe58b6a29R393-R401)
> add back in fuzzy file outputs

- .github/workflows/distribute.yml
- CHANGELOG.md
- Dockerfile
- environment.yml
- pyproject.toml
- src/asf_tools/__main__.py
- src/asf_tools/aws.py
- src/asf_tools/etc/entrypoint.sh
- src/asf_tools/flood_map.py
- src/asf_tools/water_map.py
- tests/test_aws.py
> Release v0.5.0

- CHANGELOG.md
- src/asf_tools/flood_map.py
> make the flood_mask includes 0, 1, and 255, where 255 is no-data value

- CHANGELOG.md
- src/asf_tools/hand/calculate.py
- tests/test_flood_map.py
- tests/test_hand.py
- tests/test_water_map.py
> determine if the nodata values in both files are nan 

- CHANGELOG.md
- src/asf_tools/flood_map.py
- src/asf_tools/hand/calculate.py
- tests/test_flood_map.py
- tests/test_hand.py
- tests/test_water_map.py
Correct nodata assignment issue in flood_map that led to inaccurate mask creation
* patch -- Patches and bugfixes for the current version that do not break current workflows
> Release v0.5.2

- tests/conftest.py
Fixes https://github.com/ASFHyP3/asf-tools/issues/193
See https://docs.pytest.org/en/stable/how-to/mark.html#registering-marks
> register pytest `integration` mark

- CHANGELOG.md
- src/asf_tools/flood_map.py
The HydroSAR team has shared new updates to the [`flood_map` code](https://drive.google.com/drive/folders/1_cqEbEK2LNsSQnY3xjvN1u4avba83NaM) to be implemented, tracked by [Tool 1433](https://asfdaac.atlassian.net/jira/software/projects/TOOL/boards/82/backlog?selectedIssue=TOOL-1433&text=flood). 
Specific changes were requested in [this PowerPoint](https://docs.google.com/presentation/d/1Ag1zBbLfS-EwgKqIMJTCa2wWrbfDVMtD/edit#slide=id.p3), but more changes are reflected in the latest iteration of the Jupyter notebook, so we will need to figure out if there are changes in the notebook that needs to be included.
> Flood Map Updates

- src/asf_tools/flood_map.py
https://docs.python.org/3/library/argparse.html#choices
> Note that inclusion in the choices sequence is checked after any [type](https://docs.python.org/3/library/argparse.html#type) conversions have been performed, so the type of the objects in the choices sequence should match the [type](https://docs.python.org/3/library/argparse.html#type) specified:
> Switch 'None' to None

- .github/workflows/create-jira-issue.yml
> Add `create-jira-issue.yml`

- CHANGELOG.md
- src/asf_tools/README.md
This PR replaces the relative link with the full URL for the watermasking readme so that the link will also work in hyp3-docs, which references this readme file for the asf_tools information page.
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release 0.7.2

- .github/dependabot.yml
> Update dependabot.yml to weekly

- .github/dependabot.yml
- .github/workflows/changelog.yml
- .github/workflows/create-jira-issue.yml
- .github/workflows/distribute.yml
- .github/workflows/labeled-pr.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tag-version.yml
- .github/workflows/test-and-build.yml
- .trufflehog.txt
- CHANGELOG.md
- environment.yml
- prototype/osl-env.yml
- pyproject.toml
> Release 0.8.0

- .github/workflows/static-analysis.yml
- CHANGELOG.md
- environment.yml
- pyproject.toml
- src/asf_tools/composite.py
- src/asf_tools/hydrosar/flood_map.py
- src/asf_tools/hydrosar/hand/calculate.py
- src/asf_tools/hydrosar/threshold.py
- src/asf_tools/hydrosar/water_map.py
- src/asf_tools/raster.py
- src/asf_tools/tile.py
- src/asf_tools/vector.py
- src/asf_tools/watermasking/generate_osm_tiles.py
- tests/hydrosar/conftest.py
- tests/test_raster.py
- tests/test_tile.py
> Release v0.8.2
